// List of basic LaTeX commands and commands from supported packages
// Only include commands/environments from: inputenc, fontenc, lmodern, babel, geometry, microtype, xcolor, hyperref, amsmath, amssymb, amsfonts, mathtools, physics, siunitx, mhchem, cancel, ulem, graphicx, tikz, pgfplots, subcaption, caption, booktabs, array, multicol, enumitem, fancyhdr, titlesec, url, setspace, parskip, ragged2e

export const latexCompletions = [
  // Basic LaTeX
  {label: 'section', type: 'keyword', info: 'Section heading'},
  {label: 'subsection', type: 'keyword', info: 'Subsection heading'},
  {label: 'subsubsection', type: 'keyword', info: 'Subsubsection heading'},
  {label: 'paragraph', type: 'keyword', info: 'Paragraph heading'},
  {label: 'textbf', type: 'function', info: 'Bold text'},
  {label: 'textit', type: 'function', info: 'Italic text'},
  {label: 'underline', type: 'function', info: 'Underline text'},
  {label: 'emph', type: 'function', info: 'Emphasize text'},
  {label: 'item', type: 'keyword', info: 'List item'},
  {label: 'begin', type: 'keyword', info: 'Begin environment'},
  {label: 'end', type: 'keyword', info: 'End environment'},
  {label: 'label', type: 'function', info: 'Label for referencing'},
  {label: 'ref', type: 'function', info: 'Reference label'},
  {label: 'cite', type: 'function', info: 'Citation'},
  {label: 'includegraphics', type: 'function', info: 'Insert image'},
  {label: 'url', type: 'function', info: 'Insert URL'},
  // Math mode basics
  {label: 'frac', type: 'function', info: 'Fraction'},
  {label: 'sqrt', type: 'function', info: 'Square root'},
  {label: 'sum', type: 'function', info: 'Sum symbol'},
  {label: 'int', type: 'function', info: 'Integral symbol'},
  {label: 'lim', type: 'function', info: 'Limit'},
  {label: 'sin', type: 'function', info: 'Sine'},
  {label: 'cos', type: 'function', info: 'Cosine'},
  {label: 'tan', type: 'function', info: 'Tangent'},
  {label: 'log', type: 'function', info: 'Logarithm'},
  {label: 'exp', type: 'function', info: 'Exponential'},
  // amsmath, amssymb, amsfonts, mathtools
  {label: 'align', type: 'keyword', info: 'Align environment'},
  {label: 'gather', type: 'keyword', info: 'Gather environment'},
  {label: 'cases', type: 'keyword', info: 'Cases environment'},
  {label: 'mathbb', type: 'function', info: 'Blackboard bold'},
  {label: 'mathcal', type: 'function', info: 'Calligraphic font'},
  {label: 'mathfrak', type: 'function', info: 'Fraktur font'},
  {label: 'mathscr', type: 'function', info: 'Script font'},
  {label: 'mathsf', type: 'function', info: 'Sans-serif font'},
  {label: 'mathrm', type: 'function', info: 'Roman font'},
  {label: 'mathbf', type: 'function', info: 'Bold font'},
  {label: 'boldsymbol', type: 'function', info: 'Bold symbol'},
  // physics, siunitx, mhchem, cancel, ulem
  {label: 'qty', type: 'function', info: 'Quantity (physics)'},
  {label: 'si', type: 'function', info: 'SI unit (siunitx)'},
  {label: 'num', type: 'function', info: 'Number (siunitx)'},
  {label: 'ce', type: 'function', info: 'Chemical equation (mhchem)'},
  {label: 'cancel', type: 'function', info: 'Cancel (strike out)'},
  {label: 'sout', type: 'function', info: 'Strike out (ulem)'},
  // xcolor, tikz, pgfplots
  {label: 'color', type: 'function', info: 'Set color'},
  {label: 'definecolor', type: 'function', info: 'Define color'},
  {label: 'tikzpicture', type: 'keyword', info: 'TikZ environment'},
  {label: 'pgfplotsset', type: 'function', info: 'PGFPlots settings'},
  // geometry, microtype, lmodern, fontenc, inputenc, babel, graphicx, subcaption, caption, booktabs, array, multicol, enumitem, fancyhdr, titlesec, url, setspace, parskip, ragged2e
  {label: 'geometry', type: 'function', info: 'Page geometry'},
  {label: 'microtype', type: 'function', info: 'Micro-typography'},
  {label: 'usepackage', type: 'function', info: 'Include package'},
  {label: 'setmainfont', type: 'function', info: 'Set main font'},
  {label: 'setlength', type: 'function', info: 'Set length'},
  {label: 'captionsetup', type: 'function', info: 'Caption setup'},
  {label: 'subcaption', type: 'keyword', info: 'Subcaption environment'},
  {label: 'captionof', type: 'function', info: 'Caption of'},
  {label: 'toprule', type: 'function', info: 'Booktabs top rule'},
  {label: 'midrule', type: 'function', info: 'Booktabs mid rule'},
  {label: 'bottomrule', type: 'function', info: 'Booktabs bottom rule'},
  {label: 'arraystretch', type: 'function', info: 'Array stretch'},
  {label: 'multicolumn', type: 'function', info: 'Multicolumn'},
  {label: 'multirow', type: 'function', info: 'Multirow'},
  {label: 'enumerate', type: 'keyword', info: 'Enumerate environment'},
  {label: 'itemize', type: 'keyword', info: 'Itemize environment'},
  {label: 'description', type: 'keyword', info: 'Description environment'},
  {label: 'fancyhdr', type: 'function', info: 'Fancy headers'},
  {label: 'pagestyle', type: 'function', info: 'Page style'},
  {label: 'titleformat', type: 'function', info: 'Title format'},
  {label: 'titlespacing', type: 'function', info: 'Title spacing'},
  {label: 'urlstyle', type: 'function', info: 'URL style'},
  {label: 'setstretch', type: 'function', info: 'Set line spacing'},
  {label: 'setspace', type: 'function', info: 'Set spacing'},
  {label: 'parskip', type: 'function', info: 'Paragraph skip'},
  {label: 'RaggedRight', type: 'function', info: 'Ragged right'},
  {label: 'RaggedLeft', type: 'function', info: 'Ragged left'},
  {label: 'Centering', type: 'function', info: 'Centering'},
];
