import * as React from 'react';
import { cva } from 'class-variance-authority';
import { cn } from '@/lib/utils';

const buttonVariants = cva(
  // include transform and a small duration so hover interactions animate smoothly
  'inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors duration-150 ease-in-out transform-gpu focus:outline-none focus:ring-2 focus:ring-offset-2 disabled:opacity-50 disabled:pointer-events-none',
  {
    variants: {
      variant: {
        // Avoid using `bg-primary/90` style because `bg-primary` is a custom
        // utility (CSS variable) and the `/90` opacity modifier may not be
        // generated by Tailwind. Use a standard opacity utility instead so
        // the hover style is always present in the compiled CSS.
        default: 'bg-primary text-primary-foreground hover:opacity-90 shadow-sm hover:shadow-md',
        outline: 'border border-input bg-transparent hover:bg-card/5',
        ghost: 'bg-transparent hover:bg-card/5',
      },
      size: {
        sm: 'h-8 px-3',
        md: 'h-10 px-4',
        lg: 'h-12 px-6',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  }
);

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'outline' | 'ghost';
  size?: 'sm' | 'md' | 'lg';
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(({ className, variant, size, ...props }, ref) => {
  return <button ref={ref} className={cn(buttonVariants({ variant, size, className }))} {...props} />;
});
Button.displayName = 'Button';

export { Button, buttonVariants };
